name: Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - uses: DamianReeves/write-file-action@v1.0
        with:
          path: ${{ env.home}}/_manuscripts/
          contents: |
            echo "---"
          write-mode: overwrite
